name: Pydoc Auto-Generator # Nom del procés
on: [push] # S'executa en fer push

permissions:
  contents: write # Permís per escriure la documentació al repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codi
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Instal·lar Django
        run: pip install django # Instal·lem Django al servidor virtual

      - name: Generar Pydoc
        run: |
          mkdir -p docs
          # Configurem les variables d'entorn necessàries
          export PYTHONPATH=$PYTHONPATH:.
          export DJANGO_SETTINGS_MODULE=my_site.settings
          
          # AQUESTA LÍNIA ÉS LA CLAU:
          # Forcem a Django a carregar-se abans de cridar a Pydoc
          python -c "import django; django.setup(); import pydoc; pydoc.writedoc('blog.models'); pydoc.writedoc('blog.views')"
          
          # Movem els fitxers HTML generats a la carpeta docs
          mv *.html docs/

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
