name: Pydoc Auto-Generator # Nom del procés que sortirà a la pestanya Actions
on: [push] # S'executa cada vegada que fas un 'push' de codi

permissions:
  contents: write # Permís per poder crear els fitxers de la documentació al repo

jobs:
  build:
    runs-on: ubuntu-latest # Utilitza un ordinador virtual amb Linux
    steps:
      - name: Checkout codi
        uses: actions/checkout@v3 # Copia el teu codi al servidor de GitHub

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12' # Instal·la la versió de Python que necessites

      - name: Instal·lar Django
        run: pip install django # Instal·la Django perquè Pydoc pugui llegir el teu codi

      - name: Generar Pydoc
        run: |
          mkdir -p docs # Crea la carpeta per guardar la documentació
          export PYTHONPATH=$PYTHONPATH:. # Indica a Python on és la teva carpeta del projecte
          export DJANGO_SETTINGS_MODULE=my_site.settings # Configura el fitxer de settings de Django
          
          # ARREGLA L'ERROR 'Apps aren't loaded yet': Inicialitza Django abans de Pydoc
          python -c "import django; django.setup()" 
          
          # Genera els fitxers HTML de la documentació de models i vistes
          python -m pydoc -w blog.models blog.views
          
          # Mou els fitxers generats a la carpeta docs
          mv *.html docs/

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Publica la carpeta docs a internet (GitHub Pages)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
